name: prueba_tecnica_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  hooks_riverpod: ^3.0.3
  http: ^1.6.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.4

dev_dependencies:
  build_runner: ^2.7.1
  dart_code_linter: ^3.1.1
  fake_async: ^1.3.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0

flutter:
  uses-material-design: true
